### ISSUE TITLE
AdapterError: Record does not satisfy unique constraints

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails-redis#39]
I get this error when creating a model with no unique constraints at all, except for `autoPK: true`. The exact same app is tested and working fine with `sails-postgresql`, `sails-disk`, and `sails-memory`.

```
Error (E_UNKNOWN) :: Encountered an unexpected error
AdapterError: Record does not satisfy unique constraints
  at /home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/lib/database/index.js:777:41
  at /home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/index.js:1138:13
  at try_callback (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/index.js:573:9)
  at RedisClient.return_reply (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/index.js:661:13)
  at ReplyParser.<anonymous> (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/index.js:309:14)
  at ReplyParser.emit (events.js:95:17)
  at ReplyParser.send_reply (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/lib/parser/javascript.js:300:10)
  at ReplyParser.execute (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/lib/parser/javascript.js:211:22)
  at RedisClient.on_data (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/index.js:534:27)
  at Socket.<anonymous> (/home/tjwebb/workspace/xtuple/xtuple-api/node_modules/sails-redis/node_modules/redis/index.js:91:14)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

**Comment by Ryanc1256** [comment]
This should be fixed in PR #67

**Comment by FabienHenon** [comment]
Hi,

I got a similar issue with my model.

It's a simple session model but when I retrieve it and update one of its attributes i get the following exception : 

```
Error (E_UNKNOWN) :: Encountered an unexpected error
AdapterError: Record does not satisfy unique constraints
at /path/to/project/node_modules/sails-redis/lib/database/index.js:787:41
at /path/to/project/node_modules/sails-redis/node_modules/redis/index.js:1170:13
at try_callback (/path/to/project/node_modules/sails-redis/node_modules/redis/index.js:592:9)
at RedisClient.return_reply (/path/to/project/node_modules/sails-redis/node_modules/redis/index.js:685:13)
at HiredisReplyParser.<anonymous> (/path/to/project/node_modules/sails-redis/node_modules/redis/index.js:321:14)
at HiredisReplyParser.emit (events.js:107:17)
at HiredisReplyParser.execute (/path/to/project/node_modules/sails-redis/node_modules/redis/lib/parser/hiredis.js:43:18)
at RedisClient.on_data (/path/to/project/node_modules/sails-redis/node_modules/redis/index.js:547:27)
at Socket.<anonymous> (/path/to/project/node_modules/sails-redis/node_modules/redis/index.js:102:14)
at Socket.emit (events.js:107:17)
at readableAddChunk (_stream_readable.js:163:16)
at Socket.Readable.push (_stream_readable.js:126:10)
at TCP.onread (net.js:538:20)
```

Here is my model definition : 

```javascript
module.exports = {

  connection: 'redisServer',

  attributes: {

    token: {
      type: 'string',
      required: true
    },
    userId: {
      type: 'integer',
      required: true,
      unique: true
    },
    sessionEnd: {
      type: 'datetime',
      required: true
    }

  }
};
```

And here is the code that updates the session and that fails : 

```javascript
UserSession.findOne({ token: authorization }).exec(function(err, found) {

      if (found) {
userSession.sessionEnd = new Date();
    userSession.save()
      .catch(function(e) {
        sails.log.warn('Impossible to update session', userSession, e);
      });
}
});
```

**Comment by Ryanc1256** [comment]
@FabienHenon it's the same issue as this...

https://github.com/balderdashy/sails-redis/issues/24
