### ISSUE TITLE
Some waterline association tests are failing

### ISSUE THREAD

**Issue by Kallikrein** [balderdashy/sails-redis#91]
I'm working on a rework of index management that would allow to set an expire TTL on unique keys.
#62 

Here : 
https://github.com/Kallikrein/sails-redis

Every sails-redis tests are passing fine, but I have errors I don't understand with waterline tests :
https://travis-ci.org/Kallikrein/sails-redis

Here is the master branch failing test
https://travis-ci.org/Kallikrein/sails-redis/builds/105752673

I started outputing logs to further try and understand the error
https://travis-ci.org/Kallikrein/sails-redis/builds/105759331

```
233 passing (5s)
  2 pending
time elapsed: 5069ms
Testing Cross Adapter interface...
  Association Interface
    Belongs To Associationz
      create
  1) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: AdapterError: Record does not satisfy unique constraints
    at lib/database/indice.js:52:32
    at lib/database/indice.js:79:5
    at try_callback (node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (node_modules/redis/index.js:321:14)
    at HiredisReplyParser.execute (node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (node_modules/redis/index.js:102:14)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
Details:  Error: AdapterError: Record does not satisfy unique constraints
```

From this point on, every test are failing

**Comment by Kallikrein** [comment]
@Ryanc1256 helped me fix the previous

@particlebanana 

I now have an error triggered by : 
```javascript
redis.exists('waterline:drop:id', function(err, exists) {
          if(err) throw err;
          assert(exists);
```

I can't find when this key is set and what value it should have, I don't know how this test can't be passing (since I thought I had only modified ':index:' or ':_indicies:' keys

**Comment by Kallikrein** [comment]
It's a set of unique id, shouldn't be used anymore since sets are not compatible with expiration
