### ISSUE TITLE
Can't run sailsjs

### ISSUE THREAD

**Issue by ProofWoW** [balderdashy/sails-redis#98]
Hi, who can help me please?
I can't run sailsjs after install sails-redis and set option in connections.js
 " },
  redis: {
      port: 6379,
      host: 'localhost'
  } "
My error:

error: A hook (`orm`) failed to load!
error: TypeError: Cannot read property 'config' of undefined
    at validateModelDef (/home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/lib/validate-model-def.js:108:84)
    at /home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/lib/initialize.js:218:36
    at arrayEach (/home/*/sailsjs/node_modules/sails/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home*/sailsjs/node_modules/sails/node_modules/lodash/index.js:3345:13)
    at Array.async.auto._normalizeModelDefs (/home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/lib/initialize.js:216:11)
    at listener (/home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:605:42)
    at /home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/home/*/sailsjs/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17) [TypeError: Cannot read property 'config' of undefined]

Thanks.

**Comment by itomas** [comment]
`redis: {
    adapter: 'sails-redis',
    port: 6379,
    host: 'localhost'
  }`

Try to define adapter :) It should help

**Comment by Ryanc1256** [comment]
@ProofWoW did @itomas fix it?

**Comment by itomas** [comment]
@Ryanc1256 I am sure, that it works.

**Comment by Ryanc1256** [comment]
@itomas so i can close it?

**Comment by itomas** [comment]
@Ryanc1256 Yes :) Also update tutorial.. because @ProofWoW have used code from tutorial
